VERSIONING="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.stellar.org/federation"
AUTH_SERVER="https://api.stellar.org/auth"
TRANSFER_SERVER="https://api.stellar.org/auth"
SIGNING_KEY="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"
HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GDVWPEOTJOPRT433PX6LULEPML5AN6QJO4GCFVFK43IPRQ23NPQAUSDF"]
[DOCUMENTATION]

ORG_NAME="Mortgage S.I."
ORG_URL="multisig-879.pages.dev"
ORG_LOGO=""
ORG_DESCRIPTION="Mortgage S.I. coin is fungible, all purpose utility token of spot markets encompassing utilization for

durable goods, non durable goods, consumer durable and Consumer packaged goods (CPG).





Protocol 18 compliant and Fannie Mae conversion compliant it sits on top of the stellar network, a blockchain-based remittance company.

Remittance companies are used to offer such advantages as fast transfer time and relatively low

transaction costs.  Diversified/Private"
ORG_PHYSICAL_ADDRESS="2029 Century Park E., Los Angeles, CA 90067, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER=""
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="mortg*keybase.io"
ORG_TWITTER=""
ORG_GITHUB="https://github.com/iccol/Privlend"
ORG_OFFICIAL_EMAIL="bonded_logon.0d@icloud.com"

[[PRINCIPALS]]

name="saas"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="MORTG"
issuer="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"
display_decimals=4
attestation_of_reserve="https://stellar.expert/explorer/public/market?asset=MORTG-GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"
name="Mortgage S.I."
desc="Fungible utility token."
conditions="Verified mint. Active burn policy. Issuer may mint additional tokens. Exchangeable with "MORTG" Issuer/ GDBQC..VU and MORTG" GC3YR..FMA"
image="multisig-879.pages.dev/MORTG03.jpg"
fixed_number="1000000"
