VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

FEDERATION_SERVER="https://api.stellar.org/federation"

TRANSFER_SERVER="https://api.stellar.org/auth"

SIGNING_KEY="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"

HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GDVWPEOTJOPRT433PX6LULEPML5AN6QJO4GCFVFK43IPRQ23NPQAUSDF"]
[DOCUMENTATION]

ORG_NAME="Mortgage S.I."



ORG_URL="http://multisig-879.pages.dev"

ORG_LOGO="https://github.com/iccol/Privlend/blob/main/MORTG%20Infographic%203"

ORG_DESCRIPTION="Private"

ORG_PHYSICAL_ADDRESS="2029 Century Park E., Los Angeles, CA 90067, United States"

ORG_PHYSICAL_ADDRESS_ATTESTATION=""

ORG_PHONE_NUMBER=""

ORG_PHONE_NUMBER_ATTESTATION=""

ORG_KEYBASE="mortg*keybase.io"

ORG_TWITTER=""

ORG_GITHUB="https://github.com/iccol/Privlend"

ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]

name="saas"

email=""

keybase=""

twitter=""

github=""

id_photo_hash=""

verification_photo_hash=""

[[CURRENCIES]]
code="MORTG"
issuer="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"
display_decimals=4
name="Mortgage S.I."
desc="Fungible utility token."


conditions="Active burn policy. Issuer may mint additional tokens"
image="https://github.com/iccol/Privlend/blob/main/MORTG%20Infographic%203"
fixed_number="false"

