VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

FEDERATION_SERVER="https://api.stellar.com/federation"

TRANSFER_SERVER="https://api.stellar.com"

SIGNING_KEY="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"

HORIZON_URL="https://horizon.stellar.com"

ACCOUNTS=[

"GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"]

[DOCUMENTATION]

ORG_NAME="Mortgage S.I."



ORG_URL="http://multisig-879.pages.dev"

ORG_LOGO="https://github.com/iccol/Privlend/blob/main/MORTG%20Infographic%203"

ORG_DESCRIPTION="Private"

ORG_PHYSICAL_ADDRESS="2029 Century Park E., Los Angeles, CA 90067, United States"

ORG_PHYSICAL_ADDRESS_ATTESTATION=""

ORG_PHONE_NUMBER="+11234567890"

ORG_PHONE_NUMBER_ATTESTATION=""

ORG_KEYBASE=""

ORG_TWITTER=""

ORG_GITHUB=""

ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]

name="saas"

email=""

keybase=""

twitter=""

github=""

id_photo_hash=""

verification_photo_hash=""

[[CURRENCIES]]

code="MORTG"

issuer="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"

display_decimals=4

name="Mortgage S.I."

desc="Fungible utility token"

conditions="Active burn policy. Issuer may mint additional tokens"

image=""

fixed_number="false"
